### ISSUE TITLE
Unit test the kweb-browser communications

### ISSUE THREAD

**Issue by sanity** [kwebio/core#5]
Embarrassingly kweb currently has no unit tests.  This is due to the fact that almost every part of its lowest level code interacts with a web browser, and so testing them without using a real web browser wouldn't be very useful.

One possibility is [PhantomJS](http://phantomjs.org/).  It's a headless web browser designed for just this type of thing, and there are [Java bindings](https://github.com/moodysalem/java-phantomjs-wrapper) for it.

This ticket isn't to implement comprehensive unit tests, but rather the first step of this, which is to show that phantomjs can be used for this in conjunction with a Kotlin unit testing library like [kotlintest](https://github.com/kotlintest/kotlintesthttps://github.com/kotlintest/kotlintest).  

Just one or two example tests to show it works will be fine, and then we can all get started on implementing tests for everything else.

**Comment by sanity** [comment]
I've been experimenting with this in the "phantomjs" branch, but it's providing to be complicated due to use of async { } which by default will silently swallow exceptions (such as those thrown by assertions).

**Comment by sanity** [comment]
Note: I've disabled the one experimental unit test that uses PhantimJS as it was hanging (see [PhantomJSSpec.kt](https://github.com/sanity/kweb/blob/master/src/test/kotlin/com/github/sanity/kweb/PhantomJSSpec.kt)).

**Comment by sanity** [comment]
Possibly a better option than PhantomJS http://htmlunit.sourceforge.net/

**Comment by sanity** [comment]
I've got HtmlUnit working, but it's very temperamental - in some cases it is necessary to simulate a click when it shouldn't be.  This might be a more reliable option, although not sure if it will work with Travis CI: https://zeroturnaround.com/rebellabs/java-integration-testing-with-testcontainers/

**Comment by DALDEI** [comment]
Suggestion - its clunky and 'old fashioned' but otoh it reliable and non-invasive.
Selenium (and various ports of it) 
It does require (or work vastly better with) a 'real browser' -- which is why its overlooked.
(pita to setup automated physical displays )
But it does work with a variety of emulated displays and environments including docker.
You can (in theory -- usually)  create a docker image with xfb and firefox that runs self-contained and fully automated once you create the test cases (usually manually).
The engine works at a fairly low level interface in the browser that has access to the full DOM and events, generally from the perspective of a user.  I dont think you can trap javascript level method calls but you can simulate user input (mouse, key) then watch for arbitrary changes in the DOM via css or xpath like selectors.

**Comment by sanity** [comment]
All very useful, thank you @DALDEI.  One practical benefit of htmlunit that I should have mentioned before is that it will run on travis-ci without doing anything fancy, because it all runs inside the JVM.

However, travis-ci might be more flexible than I imagine, or alternatively, perhaps we just bite the bullet and move the browser testing outside travis-ci to a more flexible mechanism.
